### ISSUE TITLE
Massive Amount of Dev Dependencies and Too large - Can't install

### ISSUE THREAD

**Issue by osseonews** [swellstores/horizon#21]
Thanks for the hard work on this repo. It looks very promising. I believe, though, that there is simply too many dev dependencies for this and it's just too much for one repo. Just tried to install this locally and it took over 5 minutes to install locally and then just failed out of nowhere. Couldn't even get it to actually work (and I've installed dozens of NextJs repos), so I gave up. Nowadays, if I can't get something to work in 5 minutes, I'm done. 

I think that the amount of packages here is simply too big and unnecessary. Average user just wants a frontend that works. They don't need storybook etc. does anyone actually use quizzes for an ecommerce store? This doesn't seem like a feature that would be widely used.  Maybe consider having two repos: one for developers that want to mess around with storybook etc and a lighter version for users who just want a simple store.  Or maybe split stuff up into separate packages, so a simple store can be set up and running quickly?

Point is, alot of this repo doesn't actually need to be installed on a basic site. it's way too much bloat for the average user which will make it very difficult to use. Thanks.

**Comment by AdrianRC** [comment]
Hi @osseonews, thanks for the feedback and I'm sorry to hear that you haven't had a great experience with the project so far. Please keep in mind though, that Horizon is meant to serve a wide group of users with very varied use-cases, and we need to make sure that those needs are met. Storybook or the Quiz might not be useful to you but other users have shown a lot of excitement over these features, as they came from user requests in the first place. These features shouldn't affect your experience however, as you'll only run into them if you do choose to use them. The long-running install process is more likely to have been caused by the `prepare` script, which installs linters, syncs the local repository with the editor and fetches your store's schemas to provide end-to-end type safety. If you could please share the commands you tried to run and the logs you received then we could help you with debugging the issue. Please keep in mind though that Horizon is still in beta and we're aware of how the experience is not yet where we want it to be. 

We do hear you loud and clear however regarding how we need to make building simple sites easier and faster, and that's something we're currently prioritizing and actively working on. Stay tuned as it should hopefully be what you're looking for.
